accounts/urls.py
#THIS IS THE APP - ACCOUNTS: URLS.PY FILE


from django.urls import path 

 
from django.contrib.auth.views import LoginView, LogoutView #from django.contrib.auth import views as auth_views   


from accounts.views import signup #this is the view in views.py (from App - Accounts: Views.PY. Now add the 'signup' path below...)

urlpatterns = [

path ("login/", LoginView.as_view(),  name = "login"),
path ("logout/", LogoutView.as_view(), name = "logout"), 

path ('signup/', signup, name="signup"),   # Now its wired up from App -Accounts: Views.py  (signup is the name of the FUNCTIONAL View on that page)



]

expenses/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 
#from receipts.views import ReceiptListView
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy
#from django.contrib.auth.mixins import LoginRequiredMixin
#from django.contrib.auth import views as auth_views

urlpatterns = [
    
    #path('accounts/login', include('login.urls')),
    path('login/', RedirectView.as_view(url="logout")),
    path('logout/', RedirectView.as_view(url="login")),
    path('', RedirectView.as_view(url=reverse_lazy("home")), name ="home"),
    path('accounts/', include('accounts.urls')),
    path('receipts/', include('receipts.urls')),
    path('admin/', admin.site.urls),
]

receipts/urls.py
#THIS IS THE APP - RECEIPTS: URLS.PY FILE 

from django.urls import path 
 
#from django.contrib.auth.views import 

from receipts.views import ReceiptListView, ReceiptCreateView



urlpatterns = [

path ('', ReceiptListView.as_view(), name = "home"),


#Register that RceiptCreateView for the path "create/" in the receipts urls.py and the name "create_receipt"
path ("create/", ReceiptCreateView.as_view(), name = "create_receipt")

]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings  
#from django.contrib.auth.mixins import LoginRequiredMixin

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, related_name="categories", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(USER_MODEL, related_name="accounts", on_delete=models.CASCADE)

    def __str__(self):
        return self.name 

class Receipt(models.Model):
    vendor = models.CharField(max_length=200) 
    total = models.DecimalField(max_digits=10, decimal_places=3)  
    tax = models.DecimalField(max_digits=10, decimal_places=3)  
    date = models.DateTimeField()
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE)
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE)
    account = models.ForeignKey("Account", related_name="receipts", on_delete=models.CASCADE, null = True)

accounts/views.py
#THIS IS THE APP - ACCOUNTS: VIEWS.PY FILE

from django.contrib.auth.forms import UserCreationForm  #You'll need to import the UserCreationForm from the built-in auth forms 

from django.shortcuts import render, redirect  #imported to be able to render and redirect below. Both render and redirect must be returned or nothing will be sent back to the browser. 

from django.contrib.auth.models import User #need to get someones username and password 

from django.contrib.auth import login #to allow user logins 


#You'll need to use the special create_user  method to create a new user account from their username and password
def signup(request):  #request is the incoming browser request. Need to wire it up in URLs.py of App  
    
    if request.method == 'POST':
        print(request.method)
        print(request.post)
        formvar = UserCreationForm(request.POST) #process the data from the form 
        if formvar.is_valid(): #validating signup credentials 
            user = formvar.save #this will save the user to the DB
            login(request, user) #this will login that saved user 
            return redirect("home")  #After you have created the user, redirect the browser to the path registered with the name "home" 
    else:     
        formvar = UserCreationForm()#show the blank form 
            
    return render(request, "registration/signup.html", {"form": formvar})  #this is the 'context' calling form.as_p inside signup.html form (.as_p just returns a bunch of html). This is a dictionary with "form" as key and formvar as value. The key "form" becomes a variable in the signup.html file holding an instance of the UserCreationForm - formvar 

receipts/views.py
from django.views.generic import ListView, CreateView  
from receipts.models import Receipt 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect 
 


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt 
    template_name = "receipts/list.html"
    context_object_name = 'receipts' 
    
    #def get_context_data(self, **kwargs): 
        #context = super().get_context_data(**kwargs)
        #context["title"] = "Receipts"
        #return context   (this allows to grab mroe context and modify it before sending to the screen)

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)
    #Change the queryset of the view to filter the Receipt objects where purchaser equals the logged in user


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"] 
    

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user 
        item.save()
        return redirect("home")


    #from 2 shot reference guide on Create views 
    ## Redirects to the detail page for the
    # instance just created, assuming that
    # the path name is registered
    #def get_success_url(self):
        #return reverse_lazy("model_name_detail", args=[self.#object.id])

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
<body>
  <header>
    <nav>
      <ul class="navigation">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'signup' %}">Sign Up</a>
        </li>  
        <li class="nav-item">
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </header>  
  
  
  {% block content %}
  {% endblock content %}
</body>
</html>

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
 
  </header>
    {% block content %}

    
    {% endblock content %}
</body>

</html>

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <H1>Create Receipt</H1>
             <form method = "POST">
                {% csrf_token %}
                {{ form.as_p}}
            <button type="sumbit">Create</button>
             </form>   
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}  
{% block content %}   
    <main>
        <h1>My Receipts</h1>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Vendor</th>
                        <th>Total</th>
                        <th>Tax</th>
                        <th>Date</th>
                        <th>Category</th>
                        <th>Account</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receipts in receipt_list %}
                    <tr>
                        <td>{{ receipt.vendor }}</td>
                        <td>{{ receipt.total }}</td>
                        <td>{{ receipt.tax }}</td>
                        <td>{{ receipt.date|date:"m/d/YY" }}</td>
                        <td>{{ receipt.category }}</td>
                        <td>{{ receipt.account }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}